In [1]:
import numpy as np

In [2]:
matrix = np.random.randint(1, 21, size=(5, 5))

In [3]:
print(matrix)

[[ 2  1 11  5  6]
 [ 1 15 16  6  2]
 [ 2 11 11  4  7]
 [ 2 20 10  9 15]
 [19  5 12 17 11]]


In [4]:
array_1d = np.array([5, 10, 15, 20, 25])

In [5]:
print(array_1d)

[ 5 10 15 20 25]


In [6]:
result = matrix + array_1d

In [7]:
print(result)

[[ 7 11 26 25 31]
 [ 6 25 31 26 27]
 [ 7 21 26 24 32]
 [ 7 30 25 29 40]
 [24 15 27 37 36]]


In [8]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
vector = np.array([2, 3, 4])

In [11]:
result = matrix1 * vector 

In [12]:
print(result)

[[ 2  6 12]
 [ 8 15 24]]
