In [1]:
import numpy as np

In [3]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [9]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.array_split(arr,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [11]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
transposed = matrix.T
print("\nTransposed Matrix:\n", transposed)


Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]


In [13]:
a = np.random.rand(2, 3, 4)
print(a)

[[[0.02247626 0.90797771 0.74711469 0.76724189]
  [0.76424052 0.23866639 0.30043109 0.36146142]
  [0.7919037  0.77612251 0.41334637 0.96473997]]

 [[0.5987112  0.4042755  0.20461702 0.25212506]
  [0.46095732 0.36217714 0.11914029 0.26934973]
  [0.1160318  0.78772832 0.15009835 0.33670357]]]


In [18]:
swapped=np.swapaxes(a,1,2)
print(swapped)

[[[0.02247626 0.76424052 0.7919037 ]
  [0.90797771 0.23866639 0.77612251]
  [0.74711469 0.30043109 0.41334637]
  [0.76724189 0.36146142 0.96473997]]

 [[0.5987112  0.46095732 0.1160318 ]
  [0.4042755  0.36217714 0.78772832]
  [0.20461702 0.11914029 0.15009835]
  [0.25212506 0.26934973 0.33670357]]]


In [19]:
print("\nOriginal Shape:", a.shape)
print("New Shape after Swapping Axes:", swapped.shape)


Original Shape: (2, 3, 4)
New Shape after Swapping Axes: (2, 4, 3)
