In [1]:
import numpy as np

In [2]:
a = np.random.randint(1, 10, (4, 4)) 

In [13]:
print(a)

[[7 4 1 1]
 [5 7 1 3]
 [7 6 4 1]
 [9 4 2 4]]


In [3]:
np.linalg.det(a)

np.float64(303.00000000000017)

In [4]:
np.linalg.inv(a)

array([[ 0.21782178, -0.10561056, -0.04620462,  0.03630363],
       [ 0.04950495,  0.18811881,  0.01980198, -0.15841584],
       [-0.36633663, -0.12541254,  0.32013201,  0.10561056],
       [-0.35643564,  0.11221122, -0.07590759,  0.27392739]])

In [5]:
np.linalg.matrix_rank(a)

np.int64(4)

In [6]:
A = np.array([[3, 2, -1], 
              [2, -2, 4], 
              [-1, 0.5, -1]])
b = np.array([1, -2, 0])

In [7]:
np.linalg.solve(A,b)

array([ 1., -2., -2.])

In [10]:
eigvals, eigvecs = np.linalg.eig(A)
print("\nEigenvalues:\n", eigvals)
print("\nEigenvectors:\n", eigvecs)


Eigenvalues:
 [ 3.62952412 -3.84451968  0.21499555]

Eigenvectors:
 [[-0.96012493 -0.30609463 -0.32881538]
 [-0.20984705  0.91344955  0.74686892]
 [ 0.18472771 -0.2681716   0.57798552]]


In [11]:
l1_norm = np.linalg.norm(A, 1) 
l2_norm = np.linalg.norm(A, 2) 
print("L1 norm:", l1_norm)
print("L2 norm:", l2_norm)

L1 norm: 6.0
L2 norm: 5.126196943738645


In [12]:
Q, R = np.linalg.qr(A)
print("\nQ:\n", Q)
print("\nR:\n", R)
reconstructed_A = Q @ R
print("\nReconstructed A (should be close to original):\n", reconstructed_A)


Q:
 [[-0.80178373  0.59018034  0.0939682 ]
 [-0.53452248 -0.77853577  0.32888869]
 [ 0.26726124  0.21346949  0.93968197]]

R:
 [[-3.74165739 -0.40089186 -1.60356745]
 [ 0.          2.84416696 -3.9177929 ]
 [ 0.          0.          0.28190459]]

Reconstructed A (should be close to original):
 [[ 3.   2.  -1. ]
 [ 2.  -2.   4. ]
 [-1.   0.5 -1. ]]
