In [1]:
import numpy as np

In [3]:
a = np.random.randint(1,11,size=(3,3))
b = np.random.randint(1,11,size=(3,3))

In [10]:
print(a,"\n")
print(b,"\n")

[[10  6  9]
 [ 6  9  1]
 [ 9  2  3]] 

[[ 9 10  5]
 [ 4  8  1]
 [ 6  7  2]] 



In [11]:
a+b

array([[19, 16, 14],
       [10, 17,  2],
       [15,  9,  5]], dtype=int32)

In [12]:
a-b

array([[ 1, -4,  4],
       [ 2,  1,  0],
       [ 3, -5,  1]], dtype=int32)

In [13]:
np.transpose(a)

array([[10,  6,  9],
       [ 6,  9,  2],
       [ 9,  1,  3]], dtype=int32)

In [15]:
np.linalg.det(a)

np.float64(-424.9999999999998)

In [16]:
np.linalg.det(b)

np.float64(-38.99999999999999)

In [17]:
np.dot(a,b)

array([[168, 211,  74],
       [ 96, 139,  41],
       [107, 127,  53]], dtype=int32)

In [18]:
a @ b

array([[168, 211,  74],
       [ 96, 139,  41],
       [107, 127,  53]], dtype=int32)