In [1]:
import numpy as np

In [2]:
np.random.randint(1,10)

7

In [4]:
np.random.randint(1,20,(3,3))

array([[11, 11, 12],
       [13, 13,  9],
       [ 1, 11, 12]], dtype=int32)

In [5]:
np.random.rand()

0.9729639697027106

In [7]:
np.random.rand(3,3)

array([[0.11425134, 0.55588344, 0.32884477],
       [0.57207209, 0.79012775, 0.1750099 ],
       [0.12470588, 0.58467829, 0.81102463]])

In [8]:
np.random.randn(3,3)

array([[-3.47874177,  0.78741406, -0.44022051],
       [-1.04388005, -0.40073692,  0.8246123 ],
       [-0.66792271,  0.03235139, -0.54099511]])

In [9]:
elements = ['apple', 'banana', 'cherry', 'date', 'elderberry']
np.random.choice(elements)

np.str_('elderberry')

In [10]:
np.random.choice(elements, 3, replace=False)

array(['elderberry', 'cherry', 'banana'], dtype='<U10')

In [12]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[5 1 3 2 4]


In [13]:
s=np.random.permutation(arr)
print(s,"\n")
print(arr)

[5 2 4 3 1] 

[5 1 3 2 4]


In [14]:
np.random.dirichlet(np.ones(5))

array([0.32134792, 0.37421675, 0.19283407, 0.0809243 , 0.03067696])

In [17]:
x=np.random.seed(42)
print(x)

None
